### ISSUE TITLE
lifetime issues

### ISSUE THREAD

**Issue by 007vasy** [007vasy/solana-bigtable-decode#2]
https://github.com/007vasy/solana-bigtable-decode/blob/demo/bigtable-iteraction-with-simple-func/src/bigtable_wrappers.rs#L307..L329

it's a lifetime issue but I could not reproduce it with unit tests and the LedgerStore object does not allows any lifetime to force

**Comment by 007vasy** [comment]
@drbh

**Comment by drbh** [comment]
@007vasy can you share the exact error? 

The only thing I can think of when reading the code is the two `tokio::runtimes` that you're using. 

Inside of `test_get_signature_status_functional` I think the first instance of the `rt` is dropped at the end of `create_client`, then when you pass the `&client` into the `get_signature_status_using_client` the second runtime it expects the client to have a living runtime (due to some logic inside of `LedgerStorage`) and throws an error because the first `rt` is dropped. 

The only reason I think this, is because in the working function the `rt` is not dropped until the end of `test_get_signature_status_manual`, so when the `&client` is passed to `get_signature_status_using_client` the original `rt` may still be alive and things function properly. 

However this is just a theory.... I think it best if you used a single `tokio::runtime` and only use `block_on` at the end of the function so you can return data to Python. For instance you may be able to write a `async` function that uses `async/await` on `LedgerStorage::new`, and on `get_signature_status`, then just `block_on` that whole function.


I'd look really similar to your `_get_signature_status_wrapper` function and be something like
```rust
async fn _create_and_query(signature_raw: &str) -> Result<TransactionStatus, Error> {
    let sixty_sec = Duration::new(60, 0);
    let path = String::from("./solana-sandbox-86de2dfd579b.json");
    let signature = Signature::from_str(signature_raw)?;

    let connection = LedgerStorage::new(true, Some(sixty_sec), Some(path)).await?;
    let txstatus = connection.get_signature_status(&signature).await?;

    txstatus
}

... 

#[test]
fn test() {
    let rt = get_runtime();
    let txstat = rt.block_on(_create_and_query("2jucFJFnV7CyXH9X1esPfiou8hBqotNtQUUdfRAoASqtnYv6PnRKQF2deKZd4wmh99HtqBbNmChcp3KSV9EvwtzS")).expect("should return");
    assert_eq!(txstat.slot, 121694573)
}
```

but idk 🤷‍♀️, its hard to tell without being able to run things

**Comment by 007vasy** [comment]
`thread 'bigtable_wrappers::tests::test_get_signature_status_functional' panicked at 'called `Result::unwrap()` on an `Err` value: BigTableError(Rpc(Status { code: Unknown, message: "Service was not ready: transport error", source: None }))', src/bigtable_wrappers.rs:243:101`

**Comment by 007vasy** [comment]
yes the point is I want to reuse the client and not create a new one at every call

**Comment by 007vasy** [comment]
@drbh your a fcking genius, the different runtime was the problem

**Comment by drbh** [comment]
wooo 🙌 💪 

I'm glad you were able to resolve it!
